### ISSUE TITLE
факап связи таблиц

### ISSUE THREAD

**Issue by ironalex2102** [student-archive/backend#18]
- "может ли быть закольцованная связь между несколькими таблицами"
- "нужна ли отдельная таблица с модераторами"

**Comment by ironalex2102** [comment]
Мы с Темой поняли по какому принципу нам Проскурина говорила, что не бывает такого сочетания таблиц 1 to 1 (user, student, moderator). модератор должен уйти в роль, при встречи расскажем. Таблица со связями нам помогла

**Comment by dadyarri** [comment]
Насчет модераторов появилась идея: **Может утащить поле с ролью в таблицу `user`**, чтобы не создавать Студента Модератору (а значит и левую группу. Тогда можно будет оставить `group_id` обязательным
